-- Constante do Role Softway
DEFINE ROLE_SOFTWAY = RSFWV12

-- Constantes para Conex√£o
DEFINE TNS = ORACMW

-- Maquina
DEFINE USER_MACHINE = SERVIDOR

-- Usu√°rios Padr√£o
DEFINE SOFT_USER = SFWV12
DEFINE SOFT_PASS = SFWV12

DEFINE INOUT_USER = SFWIOV12
DEFINE INOUT_PASS = SFWIOV12

DEFINE IO_USER = SFWIOV12
DEFINE IO_PASS = SFWIOV12

DEFINE INTEGRACAO_USER = SFWITV12
DEFINE INTEGRACAO_PASS = SFWITV12

DEFINE IMPORT_USER = SFWISV12
DEFINE IMPORT_PASS = SFWISV12

DEFINE BROKER_USER = SFWBSV12
DEFINE BROKER_PASS = SFWBSV12

DEFINE EXPORT_USER = SFWESV12
DEFINE EXPORT_PASS = SFWESV12

DEFINE DRAWBACK_USER = SFWDBV12
DEFINE DRAWBACK_PASS = SFWDBV12

DEFINE CAMBIO_IMP_USER = SFWCIV12
DEFINE CAMBIO_IMP_PASS = SFWCIV12

DEFINE CAMBIO_EXP_USER = SFWCEV12
DEFINE CAMBIO_EXP_PASS = SFWCEV12

DEFINE CST_USER = SFWCSTV12
DEFINE CST_PASS = SFWCSTV12

DEFINE USUARIO_SOMBRA_USER = SSFWV12
DEFINE USUARIO_SOMBRA_PASS = SFWV12

DEFINE TRACKING_USER = SFWTSV12
DEFINE TRACKING_PASS = SFWTSV12

DEFINE REPETRO_USER = SFWRPV12
DEFINE REPETRO_PASS = SFWRPV12

DEFINE RECOF_USER = SFWRFV12
DEFINE RECOF_PASS = SFWRFV12

DEFINE REGINT_USER = SFWRIV12
DEFINE REGINT_PASS = SFWRIV12

DEFINE RAF_USER = SFWRAFV12
DEFINE RAF_PASS = SFWRAFV12

-- Acrescentar ao define

-- Constantes de Tablespace
DEFINE SFW_DATA_4K = SFW_V12_DATA
DEFINE SFW_DATA_64K = SFW_V12_DATA
DEFINE SFW_DATA_128K = SFW_V12_DATA
DEFINE SFW_DATA_512K = SFW_V12_DATA
DEFINE SFW_DATA_1M = SFW_V12_DATA
DEFINE SFW_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_INDEX_1M = SFW_V12_INDEX

DEFINE SFW_IO_DATA_4K = SFW_V12_DATA
DEFINE SFW_IO_DATA_64K = SFW_V12_DATA
DEFINE SFW_IO_DATA_128K = SFW_V12_DATA
DEFINE SFW_IO_DATA_512K = SFW_V12_DATA
DEFINE SFW_IO_DATA_1M = SFW_V12_DATA
DEFINE SFW_IO_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_IO_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_IO_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_IO_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_IO_INDEX_1M = SFW_V12_INDEX

DEFINE SFW_IMPORT_DATA_4K = SFW_V12_DATA
DEFINE SFW_IMPORT_DATA_64K = SFW_V12_DATA
DEFINE SFW_IMPORT_DATA_128K = SFW_V12_DATA
DEFINE SFW_IMPORT_DATA_512K = SFW_V12_DATA
DEFINE SFW_IMPORT_DATA_1M = SFW_V12_DATA
DEFINE SFW_IMPORT_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_IMPORT_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_IMPORT_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_IMPORT_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_IMPORT_INDEX_1M = SFW_V12_INDEX

DEFINE SFW_BROKER_DATA_4K = SFW_V12_DATA
DEFINE SFW_BROKER_DATA_64K = SFW_V12_DATA
DEFINE SFW_BROKER_DATA_128K = SFW_V12_DATA
DEFINE SFW_BROKER_DATA_512K = SFW_V12_DATA
DEFINE SFW_BROKER_DATA_1M = SFW_V12_DATA
DEFINE SFW_BROKER_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_BROKER_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_BROKER_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_BROKER_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_BROKER_INDEX_1M = SFW_V12_INDEX

DEFINE SFW_EXPORT_DATA_4K = SFW_V12_DATA
DEFINE SFW_EXPORT_DATA_64K = SFW_V12_DATA
DEFINE SFW_EXPORT_DATA_128K = SFW_V12_DATA
DEFINE SFW_EXPORT_DATA_512K = SFW_V12_DATA
DEFINE SFW_EXPORT_DATA_1M = SFW_V12_DATA
DEFINE SFW_EXPORT_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_EXPORT_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_EXPORT_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_EXPORT_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_EXPORT_INDEX_1M = SFW_V12_INDEX

DEFINE SFW_DRAWBACK_DATA_4K = SFW_V12_DATA
DEFINE SFW_DRAWBACK_DATA_64K = SFW_V12_DATA
DEFINE SFW_DRAWBACK_DATA_128K = SFW_V12_DATA
DEFINE SFW_DRAWBACK_DATA_512K = SFW_V12_DATA
DEFINE SFW_DRAWBACK_DATA_1M = SFW_V12_DATA
DEFINE SFW_DRAWBACK_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_DRAWBACK_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_DRAWBACK_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_DRAWBACK_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_DRAWBACK_INDEX_1M = SFW_V12_INDEX

DEFINE SFW_CAMBIO_IMP_DATA_4K = SFW_V12_DATA
DEFINE SFW_CAMBIO_IMP_DATA_64K = SFW_V12_DATA
DEFINE SFW_CAMBIO_IMP_DATA_128K = SFW_V12_DATA
DEFINE SFW_CAMBIO_IMP_DATA_512K = SFW_V12_DATA
DEFINE SFW_CAMBIO_IMP_DATA_1M = SFW_V12_DATA
DEFINE SFW_CAMBIO_IMP_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_IMP_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_IMP_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_IMP_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_IMP_INDEX_1M = SFW_V12_INDEX

DEFINE SFW_CAMBIO_EXP_DATA_4K = SFW_V12_DATA
DEFINE SFW_CAMBIO_EXP_DATA_64K = SFW_V12_DATA
DEFINE SFW_CAMBIO_EXP_DATA_128K = SFW_V12_DATA
DEFINE SFW_CAMBIO_EXP_DATA_512K = SFW_V12_DATA
DEFINE SFW_CAMBIO_EXP_DATA_1M = SFW_V12_DATA
DEFINE SFW_CAMBIO_EXP_INDEX_4K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_EXP_INDEX_64K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_EXP_INDEX_128K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_EXP_INDEX_512K = SFW_V12_INDEX
DEFINE SFW_CAMBIO_EXP_INDEX_1M = SFW_V12_INDEX

-- Constante para Login GenÈrico
DEFINE COD_SISTEMA_SOFT = 0
DEFINE COD_SISTEMA_INOUT = 500
DEFINE COD_SISTEMA_IMPORT = 9
DEFINE COD_SISTEMA_BROKER = 21
DEFINE COD_SISTEMA_EXPORT = 2
DEFINE COD_SISTEMA_DRAWBACK = 3
DEFINE COD_SISTEMA_CAMBIO_IMP = 10
DEFINE COD_SISTEMA_CAMBIO_EXP = 11
DEFINE COD_SISTEMA_TRACKING = 0
DEFINE COD_SISTEMA_CST = 802
DEFINE COD_SISTEMA_SISCOSERV = 19
DEFINE COD_SISTEMA_INTEGRACAO = 607

-- Constante para vers„o
define VERSAO_ATUAL_BG = SFW_BG_V13_R02_P00_B00  
define VERSAO_ATUAL_IO = SFW_IO_V13_R02_P00_B00  
define VERSAO_ATUAL_BS = SFW_BS_V13_R02_P00_B00  
define VERSAO_ATUAL_IS = SFW_IS_V13_R02_P00_B00  
define VERSAO_ATUAL_DB = SFW_DB_V13_R02_P00_B00  
define VERSAO_ATUAL_ES = SFW_ES_V13_R02_P00_B00  
define VERSAO_ATUAL_CE = SFW_CE_V13_R02_P00_B00  
define VERSAO_ATUAL_CI = SFW_CI_V13_R02_P00_B00  
define VERSAO_ATUAL_CST = SFW_CST_V13_R02_P00_B00  
define VERSAO_ATUAL_IT = it-comum-release-13.2.0  
define VERSAO_ATUAL_TS = SFW_TS_V13_R02_P00_B00  
define TABLE_DATA_INSTALACAO = &&SFW_DATA_128K  
